name = "Simple Style"
license = "MIT"
licenselink = "https://github.com/yanlinlin82/simple-style/blob/master/LICENSE"
description = ""
homepage = "https://yanlinlin82.github.io/webpage-templates/simple-style/"
tags = [ simple ]
features = []
min_version = "0.41"

[author]
name = "Linlin Yan"
homepage = "http://yanlinlin.cn/"
